[package]
name = "solana-storage-bigtable"
version = "1.8.14"
description = "Solana Storage BigTable"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-storage-bigtable"
edition = "2018"

[dependencies]
arc-swap = "0.4.8"
backoff = { version = "0.3.0", features = ["tokio"] }
bincode = "1.2.1"
bzip2 = "0.3.3"
enum-iterator = "0.6.0"
flate2 = "1.0.14"
goauth = "0.10.0"
log = "0.4.11"
prost = "0.8.0"
prost-types = "0.8.0"
rand_core = "0.6.2"
serde = "1.0.122"
serde_derive = "1.0.103"
smpl_jwt = "0.6.1"
solana-metrics = { git = "https://github.com/solindex/metrics.git", version = "=1.8.14" }
solana-sdk = { git = "https://github.com/solindex/sdk.git", version = "=1.8.14" }
solana-storage-proto = { git = "https://github.com/solindex/storage-proto.git", version = "=1.8.14" }
solana-transaction-status = { git = "https://github.com/solindex/transaction-status.git", version = "=1.8.14" }
thiserror = "1.0"
futures = "0.3.8"
tonic = { version = "0.5.0", features = ["tls", "transport"] }
zstd = "0.5.1"

# openssl is a dependency of the goauth and smpl_jwt crates, but explicitly
# declare it here as well to activate the "vendored" feature that builds OpenSSL
# statically...
[target."cfg(not(windows))".dependencies]
openssl = { version = "0.10", features = ["vendored"] }
# ...except on Windows to avoid having to deal with getting CI past a build-time
# Perl dependency
[target."cfg(windows)".dependencies]
openssl = { version = "0.10", features = [] }

[lib]
crate-type = ["lib"]
name = "solana_storage_bigtable"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
